pthread.o: pthread.cc /home/ugb/lnberry/kos/src/src/ulib/../testoptions.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/kostypes.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/pthread.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc /home/ugb/lnberry/kos/src/src/ulib/../testoptions.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/kos/src/src/ulib/../include/kostypes.h
