pthread.o: pthread.cc \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../testoptions.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/kostypes.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/pthread.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../testoptions.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/syscalls.h \
 /home/ugb/lnberry/cpsc457/A3/kos_clean/src/ulib/../include/kostypes.h
